Update webhook with encrypted value
Signed-off-by: Jason Cameron <git@jasoncameron.dev>

diff --git a/dmoj/scripts/utils/notify b/dmoj/scripts/utils/notify
--- a/dmoj/scripts/utils/notify
+++ b/dmoj/scripts/utils/notify
@@ -10,10 +10,10 @@ function notify() {
     webhook_url="$DISCORD_WEBHOOK"
   fi
   local message_with_mention=""
-  local DISCORD_ROLE_OR_USER_ID="511724576674414600"       # todo replace with judge ID
+  local DISCORD_ROLE_OR_USER_ID="529735345600987136"       # todo replace with judge ID
 
   if [ -z "$webhook_url" ]; then
-    echo "ERROR: DISCORD_WEBHOOK environment variable not set." >&2
+    echo "ERROR: DISCORD_WEBHOOK environment variable not set. Set in /etc/environment or as an argument." >&2
     return 1
   fi
 
